Issue #24: Prevent assistant response for unauthorized requests
etendosoftware/com.etendoerp.copilot pull request #7
Opened 2024-11-08 13:19 UTC by fran-roig

ETP-696: Fixed process flow to stop execution on missing authorization token

2024-11-12 17:38 UTC, fran-roig commented
@valenvivaldi No se si los tests estan bien, se ejecutaron sin errores por lo menos. Use de ejemplo el test que hizo Javi para el RestService

2024-11-14 11:56 UTC, JaviBert approved these changes

2024-11-15 13:33 UTC, valenvivaldi commented on src-test/src/com/etendoerp/copilot/rest/CopilotJwtServletTest.java
> +import static org.mockito.Mockito.*;
import with asterisk

2024-11-15 13:34 UTC, valenvivaldi commented on src/com/etendoerp/copilot/rest/CopilotJwtServlet.java
> +    try{
do a code format

2024-11-15 13:35 UTC, valenvivaldi commented on src/com/etendoerp/copilot/rest/CopilotJwtServlet.java
> +        response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Internal server error");
No exception message in error?

2024-11-15 13:35 UTC, valenvivaldi requested changes
comments

2024-11-15 13:50 UTC, fran-roig commented
@isaiasb-etendo no me deja mergear a master, esta bien? No se si esto se publica hoy o la semana que viene

2024-11-15 18:47 UTC, valenvivaldi commented
Ive tested the fix and it solve the problem

2024-11-15 18:57 UTC, merged